// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eecocrkzjibnzhybjueb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlY29jcmt6amlibnpoeWJqdWViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NjEwMjMsImV4cCI6MjA1NzIzNzAyM30.bAGN_by0AMpDl_V1GHKYqzjw4AB6sIjG0wqoKFvnLdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);